### ISSUE TITLE
SPIKE - Determine ways to make the docs more EOS centric

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#132]
We would like to make the docs more EOS centric and thus easier to use

AC:
- Identify places to make the docs simpler by specifying EOS centric setups/code/flows
- Identify missing pieces (like how to raise a node on EOS specifically)
- Output all as comments on this ticket so devrel stakeholders can sign off on them and approve turning them into tickets
- Turn outputs into tickets

**Comment by iamveritas** [comment]
one PR that helped this was
https://github.com/eosnetworkfoundation/docs/pull/38

**Comment by lparisc** [comment]
With the exception of wharf-specific/targeted how-to's and tutorials for web applications, any new or existing efforts within the `docs` repo are EOS centric, even if they document an Antelope functionality from an EOS standpoint - this acquired more validity since the handoff. Therefore, identifying what's missing in the current docs will allow progress on this ticket, alongside #83 which is related. In no particular order:
- add (to existing) smart contract section - move up one level from getting started:
  - overview (missing)
  - add additional concepts (CRUD functionality, authentication (getauth), macro usage, etc.)
  - add new how-tos/tutorials to showcase new/current functionality:
    - deploying and testing smart contracts on a testnet (pick one [preferrably] or do all?)
    - ...add more...
- add node operator section:
  - overview
  - types of nodes
  - node setup guide (for all node setups, not just producers)
    - setup (config for each type)
    - running (for each type)
- add web application section:
  - overview
  - setup (user/admin access, config, etc.)
  - how-to guides (make wharf-specific from eosjs how-tos)
  - ...add more...

**Comment by VEG-Ginna** [comment]
As we have discussed in the past - do what is necessary to upgrade API documentation to include more fields of information
Caveat - probably needs effort from engineers to add specific information for additional fields

For example, add fields and info for:

- data type
- data format
- description
- limits
- dependencies (?)
- field length
- more ...
