### ISSUE TITLE
SPIKE - Figure out why account's guide sidebar index render has an issue

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#198]
Implement long-term solution for #195 Fix account's guide sidebar index render issue. Resolving this is of high importance due to new potential content that will be created in the future that might reproduce the same render issues. A non-scalable workaround was implemented in #195.

AC:
- Investigate why only this file has render issues
- Fix if small, or create another ticket which defines the needed fix

**Comment by iamveritas** [comment]
updates by Ovi
as of April 20th I could not repro this issue, this is the branch that I tried to reproduce it and I could not
ovi/fix-devrel#198_account_guide_sidebar

proposal from Luis:
Indeed, it doesn't seem to be an issue anymore. I was able to reproduce back when it happened though, so I added those instructions to the ticket. At this point we can just add the new title (2+ words were not possible before) and fix the links to the prefix number format. On either case fixing the issue back when it happened becomes low priority now since it's no longer happening. I would have liked to know why it was happening since it could uncover a more serious bug we're not seeing right now. I'd like to put it in the fridge for Eric to take a look eventually.

**Comment by lparisc** [comment]
Closing this ticket since it doesn't seem to be a rendering issue anymore on the Account Guide file. However, I opened new ticket https://github.com/eosnetworkfoundation/docsgen/issues/111 on `docsgen` to hopefully find and fix the root cause eventually.
