### ISSUE TITLE
Jim: Go through learnweb3

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#289]
https://learnweb3.io/

AC:

- Register (requires metamask)
- Go through course: 
  - [x] Freshman 1
  - [x] Freshman 2
  - [x] Freshman 3
  - [x] Freshman 4
  - [x] Freshman 5
  - [x] Freshman 6
  - [x] Freshman 7
  - [x] Freshman 8
  - [x] Freshman 9
  - [x] Freshman 10
  - [x] Sophmore 1
  - [x] Sophmore 2
  - [x] Sophmore 3
  - [x] Sophmore 4
  - [x] Sophmore 5
  - [x] Sophmore 6
  - [x] Sophmore 7
  - [x] Sophmore 8

**Comment by jimmckeeth** [comment]
I'm reviewing some of the pre-requisites too..... Trying to skim them quickly.

**Comment by jimmckeeth** [comment]
Feedback on learnweb3.io

- You have to reload the page sometimes to get the questions to appear (at least for me, using Brave with uBlock Origin)
- They really need to adopt EOS instead of Ethereum it takes way too long to mint the NFT when completing a level.
  - My NFTs don't appear to be showing up in my Metamask wallet. This might be an artifact of them using such a slow blockchain.
- The content is pretty good so far. It links to a lot of additional resources, some _required_, and some _recommended_. I like the interactivity of Scimba much better though.
  - Freshmen 1-5 is pretty remedial, especially since level 5 is where you learn to create a Wallet, which was required to setup your account... That really should have been 1st.
- You have to get 100% to pass a level, but the only feedback is when you scroll to the bottom and click. 
  - So you have to review the every question, which if you are stuck is very tedious, and not very helpful. 
  - Eventually I just started randomly changing answers until I got 100%. 
    - Lack of good feedback, and no penalty for wrong guesses just encourages creating a bot to automatically try every answer until it gets 100%. That defeats the learning objective, but when the tools only frustrate the process then that encourages circumvention. 
  - It should point you to the question or section you have wrong.
- When you finally do "graduate" a level, there is no button to go to the next level. This is annoying and poorly thought out. 
  - You have to either go back, and then click the next one, or scroll to the top, look at the name of the current level, and then select the next one in the list on the left.
  - The "graduate" button should move you to the next level while it is minting the NFT
 - They need a submit feedback. I've noticed a few small issues. Like none of the other levels display the number in the title on the page, but **Level 7 Intro to Solidity** does, but it is wrong. The page is titled **"Level 6 - Solidity"** 
   - The level 7 says view functions don't require gas, but in the Remix Storage sample it shows the an estimated gas on a `view` function (about 1/10th of the storage function), but when the view function is called, no gas is used. Very odd.
   - Entering some of the sample code from level 7 produces warnings. In the Conditions sample, Loop and Foo can both be `view` immutability.  Interestingly leaving `view` off of the function causes it the consume gas.
   - The Remix IDE estimates the loop function will use infinite gas, but then uses none. The estimate appears to be useless....
   - The Array sample produces warnings that the functions should be `pure` but the lesson provides no explanation for why.

**Comment by jimmckeeth** [comment]
[8 - Build your first dApp](https://learnweb3.io/courses/9a3fafe4-b5eb-4329-bdef-97b2aa6aacc1/lessons/1d8fc04a-af1b-4680-ac8b-755825d84ccc) is a mess

- formatting is all over the place
- the video version is almost 2 hours long for a 15-20 minute lesson. It really needs to be trimmed down. The first few minutes are just waiting for a live stream to start
- The instructions for "Goerli Testnet Ether" are outdated and way too complicated. 
- It suggests installing Solidity plugin for VSCode, but then has your using Remix.
- It tells you "Make sure your Metamask is connected to the Goerli Testnet" but doesn't explain how or what that means.
- fails to tell you how to get the `contract address`
- Seems like a great opportunity for Remix or some other tool to automatically define the ABI...

**Comment by jimmckeeth** [comment]
Ended up going down the [Hardhat route](https://hardhat.org/tutorial/) to see if that could simplify the testing process....
