### ISSUE TITLE
Rename welcome repo to docs

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#43]
We would like to rename `welcome` to `documentation`

AC: 
- Make sure that the docs builder uses the new path
- Rename the repository
- Talk with @ericpassmore about URL forwarding to the History (docs.eosnetwork.com/history-alternatives)

**Comment by lparisc** [comment]
It was decided as per DevRel channel conversations on 10/2/22 that the `welcome` repo should be renamed to `docs`. This carries various implications for documentation content that resides in the repos below:

- Any URL reference to `https://github.com/eosnetworkfoundation/welcome/...` should be renamed to `https://github.com/eosnetworkfoundation/docs/...`
- Any URL references to `https://docs.eosnetwork.com/welcome/...` should be renamed to `https://github.com/eosnetworkfoundation/docs/...`

Repos affected (add more if needed):
- https://github.com/AntelopeIO/leap
- https://github.com/AntelopeIO/cdt
- https://github.com/AntelopeIO/reference-contracts
- https://github.com/AntelopeIO/DUNE
- https://github.com/eosnetworkfoundation/eos-system-contracts

Once there are no more docs to update on the `AntelopeIO` org, we can also:
- remove all references to the `docs` repo in all URLs.
- add a `welcome` (or similar folder) on the `docs` repo. (this is needed to distinguish between content from `leap`, `cdt`, etc. and `welcome` content since the `leap`, `cdt`, etc. content will also reside on the `docs` repo).

Feel free to edit/add comments. @ericpassmore @nsjames @iamveritas

**Comment by ericpassmore** [comment]
Tracking code updates in eosnetworkfoundation/devdocs#49

**Comment by ericpassmore** [comment]
code updates completed. opening eosnetworkfoundation/devdocs#50 for github repository name change

**Comment by lparisc** [comment]
> Will DevRel be the owners for renaming the github repository? I can take care of all the other items.

Please create the PR to rename it. I'll create the PRs for renaming the URL references.

**Comment by ericpassmore** [comment]
Opened PR https://github.com/eosnetworkfoundation/devdocs/pull/51
after you approve the PR I will merge into main

**Comment by ericpassmore** [comment]
devdocs code merge into main, dependent issues closed

**Comment by lparisc** [comment]
Closing since all applicable renames have been applied.

**Comment by ericpassmore** [comment]
I had assumed the eosnetworkfoundation/welcome repo was being renamed as well. Is the repo staying as _welcome_?

**Comment by lparisc** [comment]
> I had assumed the eosnetworkfoundation/welcome repo was being renamed as well. Is the repo staying as _welcome_?

Oops, defeating the purpose here 😇. Indeed, the `welcome` repo must be renamed to `docs` as agreed and as the ticket title suggests. Otherwise, this won't work `COMMAND="Install_${GIT_BASE_REPO} ...`. Reopening until the actual renaming of the repo occurs. @nsjames could you please rename the `welcome` repo to `docs`? All doc references and `devdocs` scripts have been renamed accordingly, so we should be ready for the name change. It requires an admin to actually go to the `Settings` of the `welcome` repo and change the name to `docs`. I will close this ticket once it's done. Thanks for the reminder @ericpassmore

**Comment by lparisc** [comment]
Closing this ticket since the `welcome` repo has finally been renamed to `docs`.
