### ISSUE TITLE
Update the "Bios Boot Tutorial"

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#88]
Update the bios boot tutorial to reflect what it does, what it's used for, and what the usecase is

#87

**Comment by lparisc** [comment]
also related to #6

**Comment by lparisc** [comment]
Taken a bit longer than usual since:
- bios boot tutorial content was outdated as a result of cutting the old welcome repo before the LICENSE file was removed.
- outdated content did not use `eosio.boot` contract which is the current mechanism to enable protocol features.
- even using the latest content from the old `welcome` repo, the `eosio.boot` contract installation is still outdated.
- the `eosio.boot` has been integrated with both the current `reference-contracts` and `eos-system-contracts`.
