### ISSUE TITLE
Spike -  How to build your Dapps on EVM

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#92]
AC:
- Identify SMEs
- Find out what parts of the app building experience needs to be documented
- Gather all information from those parts
- Create a ticket to write the documentation
- Where does output from research need to reside

Notes: I think we have a good reference from Avalanche, the link is: https://docs.avax.network/dapps/launch-your-ethereum-dapp, and the key is that we need to confirm how many EIPs we have supported so far

**Comment by VEG-Ginna** [comment]
**Notes**:  Telegram conversation Nov 10 - https://docs.google.com/document/d/1reJTS4bhghBhJ8te60CHijp4iLFQeK8fXBu3dXNIw00/edit#heading=h.ui19ky1x31lt

**Comment by VEG-Ginna** [comment]
identical to building an app on Etherium, which has documentation

need a demo by SMEs (Josh), record demo
Need to reproduce the steps
need a day or two after demo
review cycle one or two days

**Deliverables**:
create an overview
develop smart contract section
deploy smart contract (Truffle/hardhat) - go with one, not both at this time  - go with Hardhat, need TrustEVM node running
verify smart contract
create ERC-20 fungible token

**Comment by lparisc** [comment]
The main dev (Y) requires a deliverable from another dev (K) to be able to showcase the main use case steps for building/migrating Eth dApps to TrustEVM. While technically it would be possible to create a demo using the existing framework and testnet, the main dev prefers to focus his efforts on completing the tasks on the actual mainnet and using the explorer (the task K is completing) and then showcasing the actual steps a dev would carry out in a final deployment. It was generally agreed during last Thursday's EVM+ Call meeting that this made more sense timewise, instead of working on multiple demos, the first iterations which would soon become obsolete by the time the final demo was available.
